name: Rebase groovy-dsl branch
on:
  push:
    branches:
      - kotlin-dsl
  workflow_dispatch:

jobs:
  rebase:
    if: github.repository_owner == 'gradle'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: groovy-dsl
          fetch-depth: '0'

      - name: Rebase
        run: |
          git config user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
          git config user.name "Github Actions"
          git rebase origin/kotlin-dsl
          git push --force-with-lease origin groovy-dsl
