name: Run reproducer on each commit
on: push
jobs:
  gradle-on-fedora:
    runs-on: ubuntu-24.04
    container: fedora:40
    steps:
    - name: Setup
      run: dnf install -y java-17-openjdk java-21-openjdk unzip
    - name: Debug environment
      run: |
        env | grep JAVA_HOME || true
        ls $JAVA_HOME_21_X64/bin
    - uses: actions/checkout@v4
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: 8.9
        build-scan-publish: true
        build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
        build-scan-terms-of-use-agree: "yes"
    - name: Show version
      run: gradle --version
    - name: List toolchains
      run: gradle javaToolchains
    - name: Stop daemons
      run: gradle --stop
    - name: Run build
      run: gradle classes
  gradle-on-windows:
    runs-on: windows-2022
    steps:
    - name: Debug environment
      shell: cmd
      run: |
        set | findstr /C:JAVA_HOME
        dir %JAVA_HOME_21_X64%\bin
    - uses: actions/checkout@v4
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: 8.9
        build-scan-publish: true
        build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
        build-scan-terms-of-use-agree: "yes"
    - name: Show version
      run: gradle --version
    - name: List toolchains
      run: gradle javaToolchains
    - name: Stop daemons
      run: gradle --stop
    - name: Run build
      run: gradle classes
